[project]
name = "stx-realestate-community-token"
authors = []
description = ""
telemetry = true
requirements = []
[contracts.stx-realestate-community]
path = "contracts/stx-realestate-community.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
